### ISSUE TITLE
Sharing Dockerfile to test deployment.

### ISSUE THREAD

**Issue by asolis** [StatCan/datascience-cookiecutter#38]
@goatsweater could you please share the current docker file that you are using ? (i.e., the one you showed me using the wheel)

Maybe we end up creating a version of this file inside the repository as me talked, but for now I just wanted to start testing it with other projects. 

Thanks.

**Comment by goatsweater** [comment]
Based on some recent experience in one of my projects I've begun to deviate from this template for a few different reasons, but mostly because I've found it isn't necessary to have multistage builds in practice, and this file incurs a maintenance burden that is a source of build failures.

By leveraging the CI stages directly to build a package it can be copied into the container as long the CI marks it as an artifact. This makes the Dockerfile easier to maintain by removing the entire build stage, and removing the need to maintain the package version information. It also makes the build artifact available to other stages (like tests).

I need to put a bit of effort into generalizing it so that it can be brought into this project. I'll try to get to that soon.

**Comment by goatsweater** [comment]
Closing this as gitlab CI has been integrated into the templates
